# Generated by Django 5.2.3 on 2025-07-03 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Files', '0003_alter_file_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='sentence_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='token_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='vocab_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
