# Generated by Django 5.2.3 on 2025-07-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Files', '0004_file_sentence_count_file_token_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='content',
        ),
        migrations.AddField(
            model_name='file',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
